name: build

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    uses: ./.github/workflows/setup-linux.yaml
    with:
      command: npm run build-linux-project --workspace @project-gauntlet/build
      upload-artifact: true
    secrets: inherit

  build-macos:
    uses: ./.github/workflows/setup-macos.yaml
    with:
      command: npm run build-macos-project --workspace @project-gauntlet/build
      upload-artifact: true
    secrets: inherit

  build-windows:
    uses: ./.github/workflows/setup-windows.yaml
    with:
      command: npm run build-windows-project --workspace @project-gauntlet/build
      upload-artifact: true
    secrets: inherit
